version: '3.8'

services:
  postgres-server:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  shareit-server:
    build: server
    container_name: shareit_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - postgres-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-server:5432/shareit
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSOWRD=root

  shareit-gateway:
    build: gateway
    container_name: shareit_gateway
    ports:
    - "8080:8080"
    depends_on:
    - "shareit-server"
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090
      - TZ=Europe/Moscow
