CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(100) NOT NULL,
    CONSTRAINT email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    description VARCHAR(255),
    user_id BIGINT,
    created TIMESTAMP,
    CONSTRAINT item_requests_users_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available BOOLEAN,
    user_id BIGINT,
    request_id BIGINT,
    CONSTRAINT items_users_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT items_item_requests_requeset_id_fk FOREIGN KEY (request_id) REFERENCES item_requests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    item_id BIGINT,
    user_id BIGINT,
    status VARCHAR(50),
    CONSTRAINT bookings_users_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT bookings_items_item_id_fk FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    text VARCHAR,
    item_id BIGINT,
    user_id BIGINT,
    created TIMESTAMP,
    CONSTRAINT comments_users_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT comments_items_item_id_fk FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

